CollegeLolaGonzalezControl/Models/Security/LoginInputModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CollegeLolaGonzalezControl.Models.Security
{
    public class LoginInputModel
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} no puede superar 50 caracteres")]
        [Display(Name = "Usuario de red")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Clave de red")]
        public string Password { get; set; }
    }
}

CollegeLolaGonzalezControl/Areas/QualificationManager/Controllers/QualificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CollegeLolaGonzalezControl.Areas.QualificationManager.Controllers
{
    public class QualificationController : Controller
    {
        // GET: QualificationManager/Qualification
        public ActionResult Index()
        {
            return View();
        }
    }
}

CollegeLolaGonzalezControl/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CollegeLolaGonzalezControl.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult IngresoCalificacion()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IngresoCalificacion(string Data) {

            return View(Data);
        }

        // GET: Home
        public ActionResult ResultadoCalificacion()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ResultadoCalificacion(string Data)
        {

            return View(Data);
        }


    }
}

CollegeLolaGonzalezControl/Controllers/SecurityController.cs
using CollegeLolaGonzalezControl.Models.Security;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace CollegeLolaGonzalezControl.Controllers

{


    public class SecurityController : Controller
    {

        IAuthenticationManager Authentication
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        // GET: Security
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(LoginInputModel model)
        {
            return View(model);

        }


  
        public ActionResult Logout()
        {
            Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

    }
}

CollegeLolaGonzalezControl/Areas/QualificationManager/Views/Qualification/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h3>Desarrollor Fabio Alzate</h3>
    <div> 
    </div>
</body>
</html>

CollegeLolaGonzalezControl/Views/Home/IngresoCalificacion.cshtml
@section Scripts{
    <script>
        $("#select1").change(function () {
            console.log("Entro al script")
            if ($(this).data('options') == undefined) {
                $(this).data('options', $('#select2 option').clone());
            }
            //console.log($(this).val());
            var id = $(this).val();
            var options = $(this).data('options').filter('[data-value=' + id + ']');
            //console.log(options);
            $('#selectiondiv').show();
            //document.getElementById("selectiondiv").style.display = "block";
            $('#select2').html(options).show();
        });

        function GetNote() {
            var note1 = parseFloat((document.getElementById("nota1").value));
            //var note2 = parseFloat((document.getElementById("nota2").value));

            //var notadef = (note1 + note2);
            alert(note1);
            //return notadef
        }


        /*function cal() {

            if (document.getElementById("nota1")) {
                var dump = document.getElementById("demo").value.GetNote();
            }

        }*/

    </script>
}


<div class="container">
    <h2>Ingreso Calificaciones</h2>
    <form role="form" class="form-horizontal" id="idFormIngrCal" method="~/Home/ResultadoCalificacion">

        <div class="form-group">
            <label class="col-sm-1" for="inputPassword1">Materia</label>
            <div class="col-sm-5">
                <select class="form-control" name="select1" id="select1">
                    <option value="">Seleccione la Materia</option>
                    <option value="1">Algebra y Trigonometria</option>
                    <option value="2">Calculo Diferencial</option>
                    <option value="3">Calculo Integral</option>
                    <option value="4">Ecuaciones Diferencial</option>
                    <option value="5">Metodos Numericos</option>
                </select>
            </div>
        </div>

        <div class="form-group" id="selectiondiv" style="display: none;">
            <label class="col-sm-1" for="inputPassword1">Alumno</label>
            <div class="col-sm-5">
                <select class="form-control" name="select2" id="select2" style="display: none;">
                    <option>---</option>
                    <option data-value="1">Macnelly Torres</option>
                    <option data-value="1">Franco Armani</option>
                    <option data-value="1">Alexis Henriquez</option>
                    <option data-value="1">Andres Guerra</option>
                    <option data-value="2">Matheus Uribe</option>
                    <option data-value="2">Diego Arias</option>
                    <option data-value="2">Alexander Mejia</option>
                    <option data-value="3">Farid Diaz</option>
                    <option data-value="3">Wilson Borja</option>
                    <option data-value="3">Marlos Moreno</option>
                    <option data-value="4">Sebastian Perez</option>
                    <option data-value="4">Andres Ibargue</option>
                    <option data-value="4">Daniel Bocanegra</option>
                    <option data-value="4">Davinson Sanchez</option>
                    <option data-value="5">Felipe Aguilar</option>
                    <option data-value="5">Victor Ibarbo</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3"><label>Nota 1</label><input type="text" class="form-control" id="nota1" name="nota1" placeholder="Ingrese Nota" onchange="cal()"/></div>
            <div class="col-sm-3"><label>Nota 2</label><input type="text" class="form-control" id="nota2" name="nota2" placeholder="Ingrese Nota" onchange="cal()"/></div>
            <div class="col-sm-3"><label>Nota 3</label><input type="text" class="form-control" placeholder="Ingrese Nota"></div>
            <div class="col-sm-3"><label>Nota 4</label><input type="text" class="form-control" placeholder="Ingrese Nota"></div>
            <div class="col-sm-3"><label>Nota 4</label><input type="text" class="form-control" id="notdef" name="notdef" placeholder="Nota Definitiva"></div>
        </div>
        <div class="form-group">
            <div class="col-sm-6">
                <!--<button type="submit" class="btn btn-danger pull-right" value="Submit" id="submitBtn" data-toggle="modal" data-target="#exampleModalLong">Enviar</button>-->
                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">CALCULAR</button>
            </div>
        </div>


        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">RESULTADO </h4>
                    </div>
                    <div class="modal-body">
                        <p>La Calificacion total es : </p>
                        <p id="demo"> </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Enviar</button>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>

CollegeLolaGonzalezControl/Views/Home/ResultadoCalificacion.cshtml
@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ResultadoCalificacion</title>
</head>
<body>
    <div> 
        <h3>Resultado</h3>
    </div>
</body>
</html>

CollegeLolaGonzalezControl/Views/Security/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon.png">
    <title>Material Pro Admin Template - The Most Complete & Trusted Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core /css -->
    <script src="/assets/plugins/jquery/jquery.min.js"></script>

    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom /css -->
    <link href="/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="/css/colors/default-dark.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond./js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">
    <aside class="left-sidebar">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <div class="sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar">
                    <ul id="sidebarnav">
                        <li class="nav-small-cap">DOCUMENTATION</li>
                        <li><a href="#Intro" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">Introduction</span></a></li>
                        <li><a href="#Intro" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">Introduction</span></a></li>
                        <li><a href="#Intro" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">Introduction</span></a></li>
                        <li><a href="#Intro" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">Introduction</span></a></li>
                        <li><a href="#Intro" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">Introduction</span></a></li>
                        <li><a href="#Intro" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">Introduction</span></a></li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            </div>

    </aside>

    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-6 col-8 align-self-center">
                    <h3 class="text-themecolor m-b-0 m-t-0">Values 0</h3>
                </div>
                <div class="col-md-6 col-4 align-self-center">
                    <h3 class="text-themecolor m-b-0 m-t-0">Values 1</h3>
                </div>
                <div class="col-md-6 col-2 align-self-center">
                    <h3 class="text-themecolor m-b-0 m-t-0">Values 1</h3>
                </div>
                <div class="col-md-6 col-1 align-self-center">
                    <h3 class="text-themecolor m-b-0 m-t-0">Values 1</h3>
                </div>
            </div>
    </div>

        <!-- ============================================================== -->
        <!-- Bootstrap tether Core JavaScript -->
        <script src="/assets/plugins/popper/popper.min.js"></script>
        <script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
        <!-- slimscrollbar scrollbar JavaScript -->
        <script src="/js/jquery.slimscroll.js"></script>
        <!--Wave Effects -->
        <script src="/js/waves.js"></script>
        <!--Menu sidebar -->
        <script src="/js/sidebarmenu.js"></script>
        <!--stickey kit -->
        <script src="/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
        <script src="/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
        <!--Custom JavaScript -->
        <script src="/js/custom.min.js"></script>
        <script src="/js/validation.js"></script>

        <!-- ============================================================== -->
        <!-- Style switcher -->
        <!-- ============================================================== -->
        <script src="/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
</body>


</html>

CollegeLolaGonzalezControl/Views/Security/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon.png">
    <title>Material Pro Admin Template - The Most Complete & Trusted Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="/css/colors/default-dark.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper">
        <div class="login-register" style="background-image:url(/assets/images/background/Imagen1.jpg);">
            <div class="login-box card">
                <div class="card-body">
                    <form class="form-horizontal form-material" id="loginform" action="~/Home/IngresoCalificacion">
                        <h3 class="box-title m-b-20">Iniciar Sesion</h3>
                        <div class="form-group ">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" required="" placeholder="Usuario de Red">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="password" required="" placeholder="Clave de Red">
                            </div>
                        </div>
                        <div class="form-group text-center m-t-20">
                            <div class="col-xs-12">
                                <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Loguearse</button>
                            </div>
                        </div>
                    </form> 
                </div>
            </div>
        </div>

    </section>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="/assets/plugins/popper/popper.min.js"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!--Custom JavaScript -->
    <script src="/js/custom.min.js"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
</body>

</html>

CollegeLolaGonzalezControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Material Pro Admin Template - The Most Complete & Trusted Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="/css/colors/blue.css" id="theme" rel="stylesheet">

    <link href="/css/overrides.css" id="theme" rel="stylesheet">

    @RenderSection("Head", false)

</head>
<body class="fix-header fix-sidebar card-no-border logo-center">
    <div id="main-wrapper">
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <div class="navbar-header-left">
                    <a class="navbar-brand text-light" href="index.html">
                        <!-- Logo icon --><b>
                            <i class="wi wi-day-sunny"></i>
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span>COLEGIO LOLA GONZALEZ</span>
                    </a>
                </div>
                <div class="navbar-collapse">
                    <ul class="nav navbar-nav ">
                        <li class="nav-item dropdown">@Html.ActionLink("Home", "Index", "Home", new { @class = "text-light" })</li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="nav-item dropdown">@Html.ActionLink("About", "About", "Home", new { @class = "text-light" })</li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="nav-item dropdown">@Html.ActionLink("Contact", "Contact", "Home", new { @class = "text-light" })</li>
                    </ul>

                </div>

                <div class="navbar-collapse collapse">

                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                    </ul>

                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ti-user"></i></a>
                            <div class="dropdown-menu dropdown-menu-right scale-up">
                                <ul class="dropdown-user">
                                    <li>
                                        <div class="dw-user-box">
                                            <div class="u-text">
                                                <h4>@User.Identity.Name</h4>

                                            </div>
                                        </div>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="/Security/Login"><i class="fa fa-power-off"></i> Logout</a></li>

                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>

            </nav>
        </header>


    </div>
    @RenderBody()
    <!--Custom JavaScript -->
    <script src="~/js/jquery-3.3.1.js"></script>
    <script src="/js/custom.min.js"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)
</body>
<footer class="footer">
    © 2018 Material Pro Admin by wrappixel.com
</footer>


</html>

CollegeLolaGonzalezControl/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@RenderSection("Head", false - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Colegio Lola Gonzalez", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Prueba", "Index", "Qualification", new { area = "QualificationManager" }, new {/* OPCION OBLIGATORIA*/ })</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            <p>AGILECODE - Desarrollador Fabio Alzate</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>